<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>online.codeisfun</groupId>
        <artifactId>message-brokers</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>rabbitmq</artifactId>
    <packaging>pom</packaging>
    <name>CodeIsFun :: Examples :: Message Brokers :: RabbitMQ</name>

    <modules>
        <module>rabbitmq-constants</module>
        <module>rabbitmq-queue-producer</module>
        <module>rabbitmq-queue-consumer</module>
        <module>rabbitmq-service-call-master</module>
        <module>rabbitmq-service-call-slave</module>
        <module>rabbitmq-pubsub-publisher</module>
        <module>rabbitmq-pubsub-subscriber</module>
    </modules>
</project>