[
  {
    "type": "enum",
    "name": "OrderStatus",
    "namespace": "online.codeisfun.serialization.avro",
    "symbols": [
      "PENDING",
      "SHIPPED",
      "DELIVERED",
      "CANCELED",
      "CONFIRMED"
    ]
  },
  {
    "type": "record",
    "name": "Customer",
    "namespace": "online.codeisfun.serialization.avro",
    "fields": [
      {
        "name": "customerId",
        "type": "int"
      },
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "email",
        "type": "string"
      },
      {
        "name": "phone",
        "type": "string"
      }
    ]
  },
  {
    "type": "record",
    "name": "OrderItem",
    "namespace": "online.codeisfun.serialization.avro",
    "fields": [
      {
        "name": "itemId",
        "type": "int"
      },
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "quantity",
        "type": "int"
      },
      {
        "name": "price",
        "type": "double"
      }
    ]
  },
  {
    "type": "record",
    "name": "Address",
    "namespace": "online.codeisfun.serialization.avro",
    "fields": [
      {
        "name": "country",
        "type": "string"
      },
      {
        "name": "state",
        "type": "string"
      },
      {
        "name": "city",
        "type": "string"
      },
      {
        "name": "street",
        "type": "string"
      },
      {
        "name": "postalCode",
        "type": "string"
      }
    ]
  },
  {
    "type": "record",
    "name": "Order",
    "namespace": "online.codeisfun.serialization.avro",
    "fields": [
      {
        "name": "orderId",
        "type": "int"
      },
      {
        "name": "customer",
        "type": "online.codeisfun.serialization.avro.Customer"
      },
      {
        "name": "items",
        "type": {
          "type": "array",
          "items": "online.codeisfun.serialization.avro.OrderItem"
        }
      },
      {
        "name": "address",
        "type": "online.codeisfun.serialization.avro.Address"
      },
      {
        "name": "status",
        "type": "online.codeisfun.serialization.avro.OrderStatus"
      },
      {
        "name": "createdAt",
        "type": "long"
      },
      {
        "name": "updatedAt",
        "type": "long"
      },
      {
        "name": "description",
        "type": "string"
      }
    ]
  }
]